import styled from 'styled-components'

export const Container = styled.div`
  place-items: center;
  width: 100vw;
  height: 100vh;

  /***************************************************
 * Generated by SVG Artista on 8/27/2023, 1:44:14 AM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net
 **************************************************/

  display: grid;
  /***************************************************
 * Generated by SVG Artista on 8/27/2023, 1:52:23 AM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net
 **************************************************/

  /***************************************************
 * Generated by SVG Artista on 9/18/2023, 4:45:48 PM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net
 **************************************************/
  /***************************************************
 * Generated by SVG Artista on 9/18/2023, 4:50:22 PM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net
 **************************************************/

  @-webkit-keyframes animate-svg-stroke-1 {
    0% {
      stroke-dashoffset: 192.3172607421875px;
      stroke-dasharray: 192.3172607421875px;
    }

    100% {
      stroke-dashoffset: 0;
      stroke-dasharray: 192.3172607421875px;
    }
  }

  @keyframes animate-svg-stroke-1 {
    0% {
      stroke-dashoffset: 192.3172607421875px;
      stroke-dasharray: 192.3172607421875px;
    }

    100% {
      stroke-dashoffset: 0;
      stroke-dasharray: 192.3172607421875px;
    }
  }

  @-webkit-keyframes animate-svg-fill-1 {
    0% {
      fill: transparent;
    }

    100% {
      fill: #4CAF50;
    }
  }

  @keyframes animate-svg-fill-1 {
    0% {
      fill: transparent;
    }

    100% {
      fill: #4CAF50;
    }
  }

  .svg-elem-1 {
    -webkit-animation: animate-svg-stroke-1 1s
        cubic-bezier(0.47, 0, 0.745, 0.715) 0s both,
      animate-svg-fill-1 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8s both;
    animation: animate-svg-stroke-1 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0s
        both,
      animate-svg-fill-1 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8s both;
  }

  @-webkit-keyframes animate-svg-stroke-2 {
    0% {
      stroke-dashoffset: 356.69921875px;
      stroke-dasharray: 356.69921875px;
    }

    100% {
      stroke-dashoffset: 0;
      stroke-dasharray: 356.69921875px;
    }
  }

  @keyframes animate-svg-stroke-2 {
    0% {
      stroke-dashoffset: 356.69921875px;
      stroke-dasharray: 356.69921875px;
    }

    100% {
      stroke-dashoffset: 0;
      stroke-dasharray: 356.69921875px;
    }
  }

  @-webkit-keyframes animate-svg-fill-2 {
    0% {
      fill: transparent;
    }

    100% {
      fill: #4CAF50;
    }
  }

  @keyframes animate-svg-fill-2 {
    0% {
      fill: transparent;
    }

    100% {
      fill: #4CAF50;
    }
  }

  .svg-elem-2 {
    -webkit-animation: animate-svg-stroke-2 1s
        cubic-bezier(0.47, 0, 0.745, 0.715) 0.12s both,
      animate-svg-fill-2 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.9s both;
    animation: animate-svg-stroke-2 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.12s
        both,
      animate-svg-fill-2 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.9s both;
  }

  @-webkit-keyframes animate-svg-stroke-3 {
    0% {
      stroke-dashoffset: 367.68011474609375px;
      stroke-dasharray: 367.68011474609375px;
    }

    100% {
      stroke-dashoffset: 0;
      stroke-dasharray: 367.68011474609375px;
    }
  }

  @keyframes animate-svg-stroke-3 {
    0% {
      stroke-dashoffset: 367.68011474609375px;
      stroke-dasharray: 367.68011474609375px;
    }

    100% {
      stroke-dashoffset: 0;
      stroke-dasharray: 367.68011474609375px;
    }
  }

  @-webkit-keyframes animate-svg-fill-3 {
    0% {
      fill: transparent;
    }

    100% {
      fill: #4CAF50;
    }
  }

  @keyframes animate-svg-fill-3 {
    0% {
      fill: transparent;
    }

    100% {
      fill: #4CAF50;
    }
  }

  .svg-elem-3 {
    -webkit-animation: animate-svg-stroke-3 1s
        cubic-bezier(0.47, 0, 0.745, 0.715) 0.24s both,
      animate-svg-fill-3 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1s both;
    animation: animate-svg-stroke-3 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.24s
        both,
      animate-svg-fill-3 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1s both;
  }

  @-webkit-keyframes animate-svg-stroke-4 {
    0% {
      stroke-dashoffset: 425.94390869140625px;
      stroke-dasharray: 425.94390869140625px;
    }

    100% {
      stroke-dashoffset: 0;
      stroke-dasharray: 425.94390869140625px;
    }
  }

  @keyframes animate-svg-stroke-4 {
    0% {
      stroke-dashoffset: 425.94390869140625px;
      stroke-dasharray: 425.94390869140625px;
    }

    100% {
      stroke-dashoffset: 0;
      stroke-dasharray: 425.94390869140625px;
    }
  }

  @-webkit-keyframes animate-svg-fill-4 {
    0% {
      fill: transparent;
    }

    100% {
      fill: black;
    }
  }

  @keyframes animate-svg-fill-4 {
    0% {
      fill: transparent;
    }

    100% {
      fill: black;
    }
  }

  .svg-elem-4 {
    -webkit-animation: animate-svg-stroke-4 1s
        cubic-bezier(0.47, 0, 0.745, 0.715) 0.36s both,
      animate-svg-fill-4 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.1s both;
    animation: animate-svg-stroke-4 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.36s
        both,
      animate-svg-fill-4 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.1s both;
  }

  @-webkit-keyframes animate-svg-stroke-5 {
    0% {
      stroke-dashoffset: 429.6834716796875px;
      stroke-dasharray: 429.6834716796875px;
    }

    100% {
      stroke-dashoffset: 0;
      stroke-dasharray: 429.6834716796875px;
    }
  }

  @keyframes animate-svg-stroke-5 {
    0% {
      stroke-dashoffset: 429.6834716796875px;
      stroke-dasharray: 429.6834716796875px;
    }

    100% {
      stroke-dashoffset: 0;
      stroke-dasharray: 429.6834716796875px;
    }
  }

  @-webkit-keyframes animate-svg-fill-5 {
    0% {
      fill: transparent;
    }

    100% {
      fill: #4CAF50;
    }
  }

  @keyframes animate-svg-fill-5 {
    0% {
      fill: transparent;
    }

    100% {
      fill: #4CAF50;
    }
  }

  .svg-elem-5 {
    -webkit-animation: animate-svg-stroke-5 1s
        cubic-bezier(0.47, 0, 0.745, 0.715) 0.48s both,
      animate-svg-fill-5 0.7s cubic-bezier(0.47, 0, 0.745, 0.715)
        1.2000000000000002s both;
    animation: animate-svg-stroke-5 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.48s
        both,
      animate-svg-fill-5 0.7s cubic-bezier(0.47, 0, 0.745, 0.715)
        1.2000000000000002s both;
  }

  @-webkit-keyframes animate-svg-stroke-6 {
    0% {
      stroke-dashoffset: 392.86334228515625px;
      stroke-dasharray: 392.86334228515625px;
    }

    100% {
      stroke-dashoffset: 0;
      stroke-dasharray: 392.86334228515625px;
    }
  }

  @keyframes animate-svg-stroke-6 {
    0% {
      stroke-dashoffset: 392.86334228515625px;
      stroke-dasharray: 392.86334228515625px;
    }

    100% {
      stroke-dashoffset: 0;
      stroke-dasharray: 392.86334228515625px;
    }
  }

  @-webkit-keyframes animate-svg-fill-6 {
    0% {
      fill: transparent;
    }

    100% {
      fill: #4CAF50;
    }
  }

  @keyframes animate-svg-fill-6 {
    0% {
      fill: transparent;
    }

    100% {
      fill: #4CAF50;
    }
  }

  .svg-elem-6 {
    -webkit-animation: animate-svg-stroke-6 1s
        cubic-bezier(0.47, 0, 0.745, 0.715) 0.6s both,
      animate-svg-fill-6 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.3s both;
    animation: animate-svg-stroke-6 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.6s
        both,
      animate-svg-fill-6 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.3s both;
  }

  @-webkit-keyframes animate-svg-stroke-7 {
    0% {
      stroke-dashoffset: 293.3673095703125px;
      stroke-dasharray: 293.3673095703125px;
    }

    100% {
      stroke-dashoffset: 0;
      stroke-dasharray: 293.3673095703125px;
    }
  }

  @keyframes animate-svg-stroke-7 {
    0% {
      stroke-dashoffset: 293.3673095703125px;
      stroke-dasharray: 293.3673095703125px;
    }

    100% {
      stroke-dashoffset: 0;
      stroke-dasharray: 293.3673095703125px;
    }
  }

  @-webkit-keyframes animate-svg-fill-7 {
    0% {
      fill: transparent;
    }

    100% {
      fill: #4CAF50;
    }
  }

  @keyframes animate-svg-fill-7 {
    0% {
      fill: transparent;
    }

    100% {
      fill: #4CAF50;
    }
  }

  .svg-elem-7 {
    -webkit-animation: animate-svg-stroke-7 1s
        cubic-bezier(0.47, 0, 0.745, 0.715) 0.72s both,
      animate-svg-fill-7 0.7s cubic-bezier(0.47, 0, 0.745, 0.715)
        1.4000000000000001s both;
    animation: animate-svg-stroke-7 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.72s
        both,
      animate-svg-fill-7 0.7s cubic-bezier(0.47, 0, 0.745, 0.715)
        1.4000000000000001s both;
  }

  @-webkit-keyframes animate-svg-stroke-8 {
    0% {
      stroke-dashoffset: 1304.5185546875px;
      stroke-dasharray: 1304.5185546875px;
    }

    100% {
      stroke-dashoffset: 0;
      stroke-dasharray: 1304.5185546875px;
    }
  }

  @keyframes animate-svg-stroke-8 {
    0% {
      stroke-dashoffset: 1304.5185546875px;
      stroke-dasharray: 1304.5185546875px;
    }

    100% {
      stroke-dashoffset: 0;
      stroke-dasharray: 1304.5185546875px;
    }
  }

  @-webkit-keyframes animate-svg-fill-8 {
    0% {
      fill: transparent;
    }

    100% {
      fill: #4CAF50;
    }
  }

  @keyframes animate-svg-fill-8 {
    0% {
      fill: transparent;
    }

    100% {
      fill: #4CAF50;
    }
  }

  .svg-elem-8 {
    -webkit-animation: animate-svg-stroke-8 1s
        cubic-bezier(0.47, 0, 0.745, 0.715) 0.84s both,
      animate-svg-fill-8 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.5s both;
    animation: animate-svg-stroke-8 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.84s
        both,
      animate-svg-fill-8 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.5s both;
  }

  @-webkit-keyframes animate-svg-stroke-9 {
    0% {
      stroke-dashoffset: 41.879425048828125px;
      stroke-dasharray: 41.879425048828125px;
    }

    100% {
      stroke-dashoffset: 0;
      stroke-dasharray: 41.879425048828125px;
    }
  }

  @keyframes animate-svg-stroke-9 {
    0% {
      stroke-dashoffset: 41.879425048828125px;
      stroke-dasharray: 41.879425048828125px;
    }

    100% {
      stroke-dashoffset: 0;
      stroke-dasharray: 41.879425048828125px;
    }
  }

  @-webkit-keyframes animate-svg-fill-9 {
    0% {
      fill: transparent;
    }

    100% {
      fill: rgb(254, 254, 254);
    }
  }

  @keyframes animate-svg-fill-9 {
    0% {
      fill: transparent;
    }

    100% {
      fill: rgb(254, 254, 254);
    }
  }

  .svg-elem-9 {
    -webkit-animation: animate-svg-stroke-9 1s
        cubic-bezier(0.47, 0, 0.745, 0.715) 0.96s both,
      animate-svg-fill-9 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.6s both;
    animation: animate-svg-stroke-9 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.96s
        both,
      animate-svg-fill-9 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.6s both;
  }

  @-webkit-keyframes animate-svg-stroke-10 {
    0% {
      stroke-dashoffset: 546.0780639648438px;
      stroke-dasharray: 546.0780639648438px;
    }

    100% {
      stroke-dashoffset: 0;
      stroke-dasharray: 546.0780639648438px;
    }
  }

  @keyframes animate-svg-stroke-10 {
    0% {
      stroke-dashoffset: 546.0780639648438px;
      stroke-dasharray: 546.0780639648438px;
    }

    100% {
      stroke-dashoffset: 0;
      stroke-dasharray: 546.0780639648438px;
    }
  }

  @-webkit-keyframes animate-svg-fill-10 {
    0% {
      fill: transparent;
    }

    100% {
      fill: rgb(254, 254, 254);
    }
  }

  @keyframes animate-svg-fill-10 {
    0% {
      fill: transparent;
    }

    100% {
      fill: rgb(254, 254, 254);
    }
  }

  .svg-elem-10 {
    -webkit-animation: animate-svg-stroke-10 1s
        cubic-bezier(0.47, 0, 0.745, 0.715) 1.08s both,
      animate-svg-fill-10 0.7s cubic-bezier(0.47, 0, 0.745, 0.715)
        1.7000000000000002s both;
    animation: animate-svg-stroke-10 1s cubic-bezier(0.47, 0, 0.745, 0.715)
        1.08s both,
      animate-svg-fill-10 0.7s cubic-bezier(0.47, 0, 0.745, 0.715)
        1.7000000000000002s both;
  }

  @-webkit-keyframes animate-svg-stroke-11 {
    0% {
      stroke-dashoffset: 690.1998291015625px;
      stroke-dasharray: 690.1998291015625px;
    }

    100% {
      stroke-dashoffset: 0;
      stroke-dasharray: 690.1998291015625px;
    }
  }

  @keyframes animate-svg-stroke-11 {
    0% {
      stroke-dashoffset: 690.1998291015625px;
      stroke-dasharray: 690.1998291015625px;
    }

    100% {
      stroke-dashoffset: 0;
      stroke-dasharray: 690.1998291015625px;
    }
  }

  @-webkit-keyframes animate-svg-fill-11 {
    0% {
      fill: transparent;
    }

    100% {
      fill: #4CAF50;
    }
  }

  @keyframes animate-svg-fill-11 {
    0% {
      fill: transparent;
    }

    100% {
      fill: #4CAF50;
    }
  }

  .svg-elem-11 {
    -webkit-animation: animate-svg-stroke-11 1s
        cubic-bezier(0.47, 0, 0.745, 0.715) 1.2s both,
      animate-svg-fill-11 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.8s both;
    animation: animate-svg-stroke-11 1s cubic-bezier(0.47, 0, 0.745, 0.715) 1.2s
        both,
      animate-svg-fill-11 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.8s both;
  }

  @-webkit-keyframes animate-svg-stroke-12 {
    0% {
      stroke-dashoffset: 1228.017822265625px;
      stroke-dasharray: 1228.017822265625px;
    }

    100% {
      stroke-dashoffset: 0;
      stroke-dasharray: 1228.017822265625px;
    }
  }

  @keyframes animate-svg-stroke-12 {
    0% {
      stroke-dashoffset: 1228.017822265625px;
      stroke-dasharray: 1228.017822265625px;
    }

    100% {
      stroke-dashoffset: 0;
      stroke-dasharray: 1228.017822265625px;
    }
  }

  @-webkit-keyframes animate-svg-fill-12 {
    0% {
      fill: transparent;
    }

    100% {
      fill: rgb(254, 254, 254);
    }
  }

  @keyframes animate-svg-fill-12 {
    0% {
      fill: transparent;
    }

    100% {
      fill: rgb(254, 254, 254);
    }
  }

  .svg-elem-12 {
    -webkit-animation: animate-svg-stroke-12 1s
        cubic-bezier(0.47, 0, 0.745, 0.715) 1.3199999999999998s both,
      animate-svg-fill-12 0.7s cubic-bezier(0.47, 0, 0.745, 0.715)
        1.9000000000000001s both;
    animation: animate-svg-stroke-12 1s cubic-bezier(0.47, 0, 0.745, 0.715)
        1.3199999999999998s both,
      animate-svg-fill-12 0.7s cubic-bezier(0.47, 0, 0.745, 0.715)
        1.9000000000000001s both;
  }
`
